CREATE TABLE IF NOT EXISTS AVERAGE_1516(
  player_id INTEGER PRIMARY KEY,
  first_name VARCHAR(50),
  last_name VARCHAR(50),
  games_played INTEGER,
  min FLOAT,
  fgm FLOAT,
  fga FLOAT,
  fg_pct FLOAT,
  fg3m FLOAT,
  fg3a FLOAT,
  fg3_pct FLOAT,
  ftm FLOAT,
  fta FLOAT,
  ft_pct FLOAT,
  oreb FLOAT,
  dreb FLOAT,
  reb FLOAT,
  ast FLOAT,
  stl FLOAT,
  blk FLOAT,
  tov FLOAT,
  aot FLOAT,
  foul FLOAT,
  pts FLOAT,
  plus_minus FLOAT
);
